defaults:
  - _self_

random_seed: 42
device: cpu

# dataset
dataset: FeMNIST
dataset_fraction: 1
min_samples_per_client: 100
distribution_type: "niid"
batch_size: 10
train_fraction: 0.6
validation_fraction: 0.2
test_fraction: 0.2
num_classes: 62

# training
num_rounds: 500
num_clients_per_round: 5
learning_rate: 0.001
epochs_per_round: null
batches_per_round: 20
same_train_test_clients: True
method: "FATS"

# unlearning
unlearning: False
unlearning_round: 350
unlearning_clients: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
unlearning_samples: None

results_dir_path: "./results/leaf_FeMNIST_FATS"
