defaults:
  - _self_

random_seed: 42
device: cpu

# dataset
dataset: shakespeare
dataset_fraction: 660
min_samples_per_client: 100
distribution_type: "niid"
batch_size: 60
train_fraction: 1.0
validation_fraction: 0.1
test_fraction: 1.0
num_classes: 80

# training
num_rounds: 50
num_clients_per_round: 20
learning_rate: 0.8
epochs_per_round: null
batches_per_round: 100
same_train_test_clients: True
method: "FATS"

# unlearning
unlearning: False
unlearning_round: 30
unlearning_clients: [0, 1, 2, 3, 4]
unlearning_samples: None

results_dir_path: "./results/leaf_shakespeare_FATS"
